server:
  port: 8081

#start:
#  active:
#    source: 'ali'
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: 'jdbc:mysql://192.168.205.20:3306/quartz?useSSL=false&useUnicode=true&characterEncoding=utf8'
    username: root
    password: '123456'
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  quartz:
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: secheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            useProperties: false
            acquireTriggersWithinLock: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 4
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

  redis:
    host: '192.168.205.20'