repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-java
    args: [--autofix, --google-java-formatter-jar=D:\jar\google-java-format-1.19.1-all-deps.jar]
