spring:
  redis:
    host: '172.29.10.180'
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
    port: 6379
security:
  model: 'interceptor'


logging:
  level:
    root: INFO
  file:
    path: classpath:logback.xml
