vertx:
  type: hazelcast
  zookeeper:
    host: '192.168.205.20'
    session-timeout: 300000
    connect-timeout: 20000
    root-path: 'io.vertx'
    retry:
      initial-sleep-time: 100
      max-times: 5
      interval-times: 10000
  hazelcast:
    config-file-path: 'classpath:cluster.xml'
  websocket:
    port: 8081
server:
  port: 8080