spring:
  data:
    mongodb:
      host: '192.168.56.20'
      port: 27017
      username: 'nebula'
      password: '123456'
      database: 'nebula'
  r2dbc:
    url: 'r2dbc:mysql://root:123456@192.168.56.20:3306/nebula?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai'
    pool:
      enabled: true
      max-size: 10

server:
  port: 8081
