spring:
  rabbitmq:
    host: '172.29.22.36'
    virtual-host: '/'
    port: 5672
    # 保障推送到exchange中成功失败都会回调
    publisher-confirm-type: correlated
    # 保障exchange送到queue中
    publisher-returns: true
    listener:
      simple:
        # 手动提交
        acknowledge-mode: manual
        retry:
          # 重试间隔
          max-interval: 10000
          # 重试次数
          max-attempts: 3
          # 重试乘法策略
          multiplier: 1
