spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: 'jdbc:mysql://192.168.205.20:3306/neptune?useSSL=false&useUnicode=true&characterEncoding=utf8'
    username: root
    password: '123456'
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  vertx:
    mysql:
      host: '192.168.56.20'
      port: 3306
      username: root
      password: '123456'
      db: 'nebula'
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update